version: '3.8'

services:

  # PostgreSQL database
  db:
    build:
      dockerfile: db/Dockerfile
      args:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    image: rgi_db
    container_name: rgc_db
    ports:
    - "5432:5432"
    networks:
      - rgnetwork

  # Node.js server
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    image: rgi_be
    container_name: rgc_be
    ports:
    - "3100:3100"
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    networks:
      - rgnetwork
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3100/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # React application
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: rgi_fe
    container_name: rgc_fe
    ports:
      - "80:3000"  # Expose frontend port
    volumes:
      - ./frontend:/frontend
#      - /frontend/node_modules
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=https://cryptafe.com
    depends_on:
      - backend
    networks:
      - rgnetwork
    restart: unless-stopped

networks:
  rgnetwork:
    driver: bridge



