version: '3.8'

services:

  # PostgreSQL database
  db:
    build:
      context: db
      dockerfile: Dockerfile
      args:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    image: rgi_db
    container_name: rgc_db
    ports:
    - "5432:5432"
    networks:
      - rgnetwork

  # Node.js server
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    image: rgi_be
    container_name: rgc_be
    ports:
    - "3100:3100"
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    networks:
      - rgnetwork
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3100/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Hardhat service
  hardhat:
    build:
      context: ./hardhat
      dockerfile: Dockerfile
    image: rgi_hh
    container_name: rgc_hh
    ports:
      - "8545:8545"  # Expose Hardhat node port
    networks:
      - rgnetwork
    volumes:
      - ./hardhat:/hardhat  # Bind host's ./hardhat to container's /hardhat
    depends_on:
      - db  # Ensure database is started before Hardhat (if needed)

  # React application
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: rgi_fe
    container_name: rgc_fe
    ports:
      - "80:3000"  # Expose frontend port
    volumes:
      - ./frontend:/frontend
#      - /frontend/node_modules
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=https://cryptafe.com
    depends_on:
      - backend
#      - hardhat
    networks:
      - rgnetwork
    restart: unless-stopped

networks:
  rgnetwork:
    driver: bridge



